# Generated by Django 3.1.7 on 2021-03-03 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortenermodel',
            name='original_url',
            field=models.URLField(max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
